name: russian_study_buddy
version: 0.0.1
description:

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  browser: ^0.10.0
  autonotify_observe: ^1.0.0+7
  polymer_elements: ^1.0.0-rc.5
  logging: any
  intl: any

transformers:
- autonotify_observe:
    entry_points:
      - web/index.html
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives